name: deploy

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Checkout
        uses: actions/checkout@v2

      - name: Setup NodeJS v16
        uses: actions/setup-node@v1
        with:
          node-version: 16
          cache: yarn

      - name: Install Dependencies
        run: yarn install

      - name: Test Build
        run: yarn build

      - name: ESlint check
        run: yarn lint

  docker:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Setup checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1.10.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: guusvanmeerveld/tempo:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
          builder: ${{ steps.buildx.outputs.name }}
          platforms: |
            linux/amd64
            linux/arm64
            linux/arm/v7

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
