name: Deploy documentation

on:
  push:
    branches:
      - master
    paths:
      - docs/**
      - .github/workflows/**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '16.6.0'

      - name: Install dependencies for bot
        run: yarn install

      - name: Install dependencies for docs
        run: yarn run docs:install

      - name: Build
        run: yarn run docs:build
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/out
