name: Deploy Docker image to Docker hub

on:
  push:
    branches:
      - master
    paths:
      - src/**
      - server/**
      - .github/workflows/**
      - Dockerfile
      - yarn.lock
      - .dockerignore
      - tsconfig.json

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Checkout
        uses: actions/checkout@v2

      - name: Setup NodeJS v16
        uses: actions/setup-node@v1
        with:
          node-version: 16
          cache: yarn

      - name: Install Dependencies
        run: yarn install

      - name: Test Build
        run: yarn build

      - name: ESlint check
        run: yarn lint

  docker:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # Login
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: guusvanmeerveld
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Build & Push
      - name: Build Dockerfile and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: guusvanmeerveld/tempo:latest

          # Cache
          cache-from: type=gha
          cache-to: type=gha,mode=max
